# Generated by Django 2.2.2 on 2019-07-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
