# Generated by Django 2.2.2 on 2019-07-15 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproducts', '0002_auto_20190714_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
